In [317]:
import networkx as nx
import numpy as np

In [ ]:
#This method finds the minimum flow1

In [318]:
def shortest_way_fan(g,s,t):
  try:
    path=nx.astar_path(g,s,t,weight='cost')
    edges=[[path[i],path[i+1]] for i in range(len(path)-1)]
    return edges
  except Exception:
    return False

In [319]:
def residual(u,f):
  return u-f+np.transpose(f)

In [320]:
def residual_cost_2(uf, c):
      n = len(uf)
      c2 = {}

      for i in range(n):
          for j in range(n):
              if uf[i][j]>0:
                  if (i,j) in c:
                      c2[i,j] = c[i,j]
                  else:
                      c2[i,j] = -c[j,i]

      return c2

In [321]:
def min_cost(u,b,c1):
  balance = b.copy()
  residualCapacity = u.copy()
  residualCosts = residual_cost_2(residualCapacity, c1)

  gamma = 2**(round(np.log2(max(balance))))

  check = len([x for x in balance if (x > 0 or x < 0)])
  while check != 0:

    residualGraph = nx.from_numpy_array(residualCapacity, create_using = nx.DiGraph)

    array_for_s = [i for i in range (len(u)) if balance[i]>=gamma]
    array_for_t = [i for i in range (len(u)) if balance[i]<=-gamma]

    for (start, end) in residualCosts.keys():
      if (start, end) in residualGraph.edges:
        residualGraph.edges[start, end]['cost'] = residualCosts[start, end]

    for s1 in array_for_s:
      for t1 in array_for_t:
        if shortest_way_fan(residualGraph,s1,t1) != False:
          s,t = s1,t1
          break

    shortest_way = shortest_way_fan(residualGraph,s,t)

    balance[s]-= gamma
    balance[t]+= gamma

    for i,j in shortest_way:
      residualCapacity[i][j] -= gamma
      residualCapacity[j][i] += gamma

    if gamma == 1:
      break
    else:
      gamma = gamma/2
      check = len([x for x in balance if (x > 0 or x < 0)])
      residualCosts = residual_cost_2(residualCapacity, c1)

  transposeResidualCapacity = np.transpose(residualCapacity)

  return transposeResidualCapacity

In [322]:
c1 = {(0, 1):1, (0, 2):2, (1, 5):5, (2, 5):-1, (3,2):3 ,(3, 4):2, (5, 4):3}
b = [10, 0, 0 ,5, -10, -5]
u = np.full((len(u),len(u)), 0.0)
for (i,j) in c1.keys():
      u[i][j] = np.inf

In [323]:
f=min_cost(u,b,c1)

In [324]:
f

array([[ 0.,  0., 10.,  0.,  0.,  0.],
       [inf,  0.,  0.,  0.,  0.,  0.],
       [inf,  0.,  0., inf,  0., 10.],
       [ 0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0., inf,  0., inf],
       [ 0., inf, inf,  0.,  5.,  0.]])

In [328]:
ftrue = np.full((len(f),len(f)), 0.0)
for i in range(len(f)):
  for j in range(len(f)):
    if f[i][j]>0 and f[i][j] != np.inf:
      ftrue[i][j] = f[i][j]
ftrue

array([[ 0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  0.]])

Задание из КТ:

In [329]:
b = np.array([10,0,0,5,-10,-5])

c1 = {(0, 1):1, (0,2):2, (1,5):5, (2,5):-1, (3,2):3, (3,4):2, (5,4):3}

for (i,j) in c1.keys():
      u[i][j] = np.inf

In [330]:
f=min_cost(u,b,c1)

In [331]:
ftrue = np.full((len(f),len(f)), 0.0)
for i in range(len(f)):
  for j in range(len(f)):
    if f[i][j]>0 and f[i][j] != np.inf:
      ftrue[i][j] = f[i][j]
ftrue

array([[ 0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  0.]])